/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Card {
  'id' : bigint,
  'setName' : string,
  'grader' : string,
  'owner' : Principal,
  'isListed' : boolean,
  'name' : string,
  'description' : string,
  'listingPrice' : [] | [bigint],
  'imageUrl' : ExternalBlob,
  'grade' : Grade,
  'rarity' : Rarity,
  'cardNumber' : string,
}
export interface CardMintInput {
  'setName' : string,
  'grader' : string,
  'name' : string,
  'description' : string,
  'imageUrl' : ExternalBlob,
  'grade' : Grade,
  'rarity' : Rarity,
  'cardNumber' : string,
}
export type ExternalBlob = Uint8Array;
export type Grade = { 'raw' : null } |
  { 'bgs9' : null } |
  { 'psa7' : null } |
  { 'psa8' : null } |
  { 'psa9' : null } |
  { 'bgs10' : null } |
  { 'bgs85' : null } |
  { 'bgs95' : null } |
  { 'psa10' : null };
export interface Listing {
  'seller' : Principal,
  'isActive' : boolean,
  'cardId' : bigint,
  'price' : bigint,
}
export interface PackTierInput {
  'rarityWeights' : {
    'ultraRare' : bigint,
    'rare' : bigint,
    'secretRare' : bigint,
    'common' : bigint,
    'uncommon' : bigint,
  },
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'imageUrl' : ExternalBlob,
  'cardCount' : bigint,
  'price' : bigint,
}
export type Rarity = { 'ultraRare' : null } |
  { 'rare' : null } |
  { 'secretRare' : null } |
  { 'common' : null } |
  { 'uncommon' : null };
export interface Redemption {
  'status' : { 'shipped' : string } |
    { 'pending' : null } |
    { 'delivered' : null } |
    { 'processing' : null },
  'owner' : Principal,
  'shippingAddress' : {
    'country' : string,
    'city' : string,
    'postalCode' : string,
    'name' : string,
    'state' : string,
    'addressLine1' : string,
    'addressLine2' : string,
  },
  'cardId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'joined' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOffer' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyCard' : ActorMethod<[bigint], undefined>,
  'createPackTier' : ActorMethod<[PackTierInput], undefined>,
  'delistCard' : ActorMethod<[bigint], undefined>,
  'deposit' : ActorMethod<[bigint], undefined>,
  'getActiveListings' : ActorMethod<[], Array<Listing>>,
  'getAllCards' : ActorMethod<[], Array<Card>>,
  'getAllRedemptions' : ActorMethod<[], Array<Redemption>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCard' : ActorMethod<[bigint], Card>,
  'getCardsByIds' : ActorMethod<[Array<bigint>], Array<Card>>,
  'getCardsByOwner' : ActorMethod<[Principal], Array<Card>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getMyRedemptions' : ActorMethod<[], Array<Redemption>>,
  'getPlatformStats' : ActorMethod<
    [],
    {
      'totalCards' : bigint,
      'activeListings' : bigint,
      'pendingRedemptions' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[Principal], boolean>,
  'listCard' : ActorMethod<[bigint, bigint], undefined>,
  'makeOffer' : ActorMethod<[bigint, bigint], bigint>,
  'mintCard' : ActorMethod<[CardMintInput], bigint>,
  'openPack' : ActorMethod<[bigint], Array<Card>>,
  'purchasePack' : ActorMethod<[string], bigint>,
  'registerUser' : ActorMethod<[string], undefined>,
  'rejectOffer' : ActorMethod<[bigint], undefined>,
  'requestRedemption' : ActorMethod<
    [
      bigint,
      {
        'country' : string,
        'city' : string,
        'postalCode' : string,
        'name' : string,
        'state' : string,
        'addressLine1' : string,
        'addressLine2' : string,
      },
    ],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transferCard' : ActorMethod<[bigint, Principal], undefined>,
  'updateRedemptionStatus' : ActorMethod<
    [
      bigint,
      { 'shipped' : string } |
        { 'pending' : null } |
        { 'delivered' : null } |
        { 'processing' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];