/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PackTierInput = IDL.Record({
  'rarityWeights' : IDL.Record({
    'ultraRare' : IDL.Nat,
    'rare' : IDL.Nat,
    'secretRare' : IDL.Nat,
    'common' : IDL.Nat,
    'uncommon' : IDL.Nat,
  }),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : ExternalBlob,
  'cardCount' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Listing = IDL.Record({
  'seller' : IDL.Principal,
  'isActive' : IDL.Bool,
  'cardId' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Grade = IDL.Variant({
  'raw' : IDL.Null,
  'bgs9' : IDL.Null,
  'psa7' : IDL.Null,
  'psa8' : IDL.Null,
  'psa9' : IDL.Null,
  'bgs10' : IDL.Null,
  'bgs85' : IDL.Null,
  'bgs95' : IDL.Null,
  'psa10' : IDL.Null,
});
export const Rarity = IDL.Variant({
  'ultraRare' : IDL.Null,
  'rare' : IDL.Null,
  'secretRare' : IDL.Null,
  'common' : IDL.Null,
  'uncommon' : IDL.Null,
});
export const Card = IDL.Record({
  'id' : IDL.Nat,
  'setName' : IDL.Text,
  'grader' : IDL.Text,
  'owner' : IDL.Principal,
  'isListed' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'listingPrice' : IDL.Opt(IDL.Nat),
  'imageUrl' : ExternalBlob,
  'grade' : Grade,
  'rarity' : Rarity,
  'cardNumber' : IDL.Text,
});
export const Redemption = IDL.Record({
  'status' : IDL.Variant({
    'shipped' : IDL.Text,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  }),
  'owner' : IDL.Principal,
  'shippingAddress' : IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
  }),
  'cardId' : IDL.Nat,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'joined' : Time,
});
export const CardMintInput = IDL.Record({
  'setName' : IDL.Text,
  'grader' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : ExternalBlob,
  'grade' : Grade,
  'rarity' : Rarity,
  'cardNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptOffer' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyCard' : IDL.Func([IDL.Nat], [], []),
  'createPackTier' : IDL.Func([PackTierInput], [], []),
  'delistCard' : IDL.Func([IDL.Nat], [], []),
  'deposit' : IDL.Func([IDL.Nat], [], []),
  'getActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getAllCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
  'getAllRedemptions' : IDL.Func([], [IDL.Vec(Redemption)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCard' : IDL.Func([IDL.Nat], [Card], ['query']),
  'getCardsByIds' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(Card)], ['query']),
  'getCardsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Card)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getMyRedemptions' : IDL.Func([], [IDL.Vec(Redemption)], ['query']),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalCards' : IDL.Nat,
          'activeListings' : IDL.Nat,
          'pendingRedemptions' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listCard' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'makeOffer' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'mintCard' : IDL.Func([CardMintInput], [IDL.Nat], []),
  'openPack' : IDL.Func([IDL.Nat], [IDL.Vec(Card)], []),
  'purchasePack' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'rejectOffer' : IDL.Func([IDL.Nat], [], []),
  'requestRedemption' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'country' : IDL.Text,
          'city' : IDL.Text,
          'postalCode' : IDL.Text,
          'name' : IDL.Text,
          'state' : IDL.Text,
          'addressLine1' : IDL.Text,
          'addressLine2' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transferCard' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'updateRedemptionStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'shipped' : IDL.Text,
          'pending' : IDL.Null,
          'delivered' : IDL.Null,
          'processing' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PackTierInput = IDL.Record({
    'rarityWeights' : IDL.Record({
      'ultraRare' : IDL.Nat,
      'rare' : IDL.Nat,
      'secretRare' : IDL.Nat,
      'common' : IDL.Nat,
      'uncommon' : IDL.Nat,
    }),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : ExternalBlob,
    'cardCount' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Listing = IDL.Record({
    'seller' : IDL.Principal,
    'isActive' : IDL.Bool,
    'cardId' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Grade = IDL.Variant({
    'raw' : IDL.Null,
    'bgs9' : IDL.Null,
    'psa7' : IDL.Null,
    'psa8' : IDL.Null,
    'psa9' : IDL.Null,
    'bgs10' : IDL.Null,
    'bgs85' : IDL.Null,
    'bgs95' : IDL.Null,
    'psa10' : IDL.Null,
  });
  const Rarity = IDL.Variant({
    'ultraRare' : IDL.Null,
    'rare' : IDL.Null,
    'secretRare' : IDL.Null,
    'common' : IDL.Null,
    'uncommon' : IDL.Null,
  });
  const Card = IDL.Record({
    'id' : IDL.Nat,
    'setName' : IDL.Text,
    'grader' : IDL.Text,
    'owner' : IDL.Principal,
    'isListed' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'listingPrice' : IDL.Opt(IDL.Nat),
    'imageUrl' : ExternalBlob,
    'grade' : Grade,
    'rarity' : Rarity,
    'cardNumber' : IDL.Text,
  });
  const Redemption = IDL.Record({
    'status' : IDL.Variant({
      'shipped' : IDL.Text,
      'pending' : IDL.Null,
      'delivered' : IDL.Null,
      'processing' : IDL.Null,
    }),
    'owner' : IDL.Principal,
    'shippingAddress' : IDL.Record({
      'country' : IDL.Text,
      'city' : IDL.Text,
      'postalCode' : IDL.Text,
      'name' : IDL.Text,
      'state' : IDL.Text,
      'addressLine1' : IDL.Text,
      'addressLine2' : IDL.Text,
    }),
    'cardId' : IDL.Nat,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'joined' : Time,
  });
  const CardMintInput = IDL.Record({
    'setName' : IDL.Text,
    'grader' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : ExternalBlob,
    'grade' : Grade,
    'rarity' : Rarity,
    'cardNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptOffer' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyCard' : IDL.Func([IDL.Nat], [], []),
    'createPackTier' : IDL.Func([PackTierInput], [], []),
    'delistCard' : IDL.Func([IDL.Nat], [], []),
    'deposit' : IDL.Func([IDL.Nat], [], []),
    'getActiveListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getAllCards' : IDL.Func([], [IDL.Vec(Card)], ['query']),
    'getAllRedemptions' : IDL.Func([], [IDL.Vec(Redemption)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCard' : IDL.Func([IDL.Nat], [Card], ['query']),
    'getCardsByIds' : IDL.Func([IDL.Vec(IDL.Nat)], [IDL.Vec(Card)], ['query']),
    'getCardsByOwner' : IDL.Func([IDL.Principal], [IDL.Vec(Card)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getMyRedemptions' : IDL.Func([], [IDL.Vec(Redemption)], ['query']),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalCards' : IDL.Nat,
            'activeListings' : IDL.Nat,
            'pendingRedemptions' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listCard' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'makeOffer' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'mintCard' : IDL.Func([CardMintInput], [IDL.Nat], []),
    'openPack' : IDL.Func([IDL.Nat], [IDL.Vec(Card)], []),
    'purchasePack' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'rejectOffer' : IDL.Func([IDL.Nat], [], []),
    'requestRedemption' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'country' : IDL.Text,
            'city' : IDL.Text,
            'postalCode' : IDL.Text,
            'name' : IDL.Text,
            'state' : IDL.Text,
            'addressLine1' : IDL.Text,
            'addressLine2' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transferCard' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'updateRedemptionStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'shipped' : IDL.Text,
            'pending' : IDL.Null,
            'delivered' : IDL.Null,
            'processing' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };