/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface PackTierInput {
    rarityWeights: {
        ultraRare: bigint;
        rare: bigint;
        secretRare: bigint;
        common: bigint;
        uncommon: bigint;
    };
    name: string;
    description: string;
    isActive: boolean;
    imageUrl: ExternalBlob;
    cardCount: bigint;
    price: bigint;
}
export interface Card {
    id: bigint;
    setName: string;
    grader: string;
    owner: Principal;
    isListed: boolean;
    name: string;
    description: string;
    listingPrice?: bigint;
    imageUrl: ExternalBlob;
    grade: Grade;
    rarity: Rarity;
    cardNumber: string;
}
export type Time = bigint;
export interface Listing {
    seller: Principal;
    isActive: boolean;
    cardId: bigint;
    price: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Redemption {
    status: {
        __kind__: "shipped";
        shipped: string;
    } | {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "delivered";
        delivered: null;
    } | {
        __kind__: "processing";
        processing: null;
    };
    owner: Principal;
    shippingAddress: {
        country: string;
        city: string;
        postalCode: string;
        name: string;
        state: string;
        addressLine1: string;
        addressLine2: string;
    };
    cardId: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CardMintInput {
    setName: string;
    grader: string;
    name: string;
    description: string;
    imageUrl: ExternalBlob;
    grade: Grade;
    rarity: Rarity;
    cardNumber: string;
}
export interface UserProfile {
    principal: Principal;
    username: string;
    joined: Time;
}
export enum Grade {
    raw = "raw",
    bgs9 = "bgs9",
    psa7 = "psa7",
    psa8 = "psa8",
    psa9 = "psa9",
    bgs10 = "bgs10",
    bgs85 = "bgs85",
    bgs95 = "bgs95",
    psa10 = "psa10"
}
export enum Rarity {
    ultraRare = "ultraRare",
    rare = "rare",
    secretRare = "secretRare",
    common = "common",
    uncommon = "uncommon"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptOffer(offerId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    buyCard(cardId: bigint): Promise<void>;
    createPackTier(tier: PackTierInput): Promise<void>;
    delistCard(cardId: bigint): Promise<void>;
    deposit(amount: bigint): Promise<void>;
    getActiveListings(): Promise<Array<Listing>>;
    getAllCards(): Promise<Array<Card>>;
    getAllRedemptions(): Promise<Array<Redemption>>;
    getBalance(): Promise<bigint>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCard(id: bigint): Promise<Card>;
    getCardsByIds(ids: Array<bigint>): Promise<Array<Card>>;
    getCardsByOwner(owner: Principal): Promise<Array<Card>>;
    getMyProfile(): Promise<UserProfile>;
    getMyRedemptions(): Promise<Array<Redemption>>;
    getPlatformStats(): Promise<{
        totalCards: bigint;
        activeListings: bigint;
        pendingRedemptions: bigint;
        totalUsers: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isRegistered(user: Principal): Promise<boolean>;
    listCard(cardId: bigint, price: bigint): Promise<void>;
    makeOffer(cardId: bigint, offerPrice: bigint): Promise<bigint>;
    mintCard(card: CardMintInput): Promise<bigint>;
    openPack(packId: bigint): Promise<Array<Card>>;
    purchasePack(tierName: string): Promise<bigint>;
    registerUser(username: string): Promise<void>;
    rejectOffer(offerId: bigint): Promise<void>;
    requestRedemption(cardId: bigint, shippingAddress: {
        country: string;
        city: string;
        postalCode: string;
        name: string;
        state: string;
        addressLine1: string;
        addressLine2: string;
    }): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transferCard(cardId: bigint, newOwner: Principal): Promise<void>;
    updateRedemptionStatus(redemptionId: bigint, status: {
        __kind__: "shipped";
        shipped: string;
    } | {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "delivered";
        delivered: null;
    } | {
        __kind__: "processing";
        processing: null;
    }): Promise<void>;
}
import type { Card as _Card, CardMintInput as _CardMintInput, ExternalBlob as _ExternalBlob, Grade as _Grade, PackTierInput as _PackTierInput, Rarity as _Rarity, Redemption as _Redemption, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptOffer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptOffer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptOffer(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async buyCard(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.buyCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buyCard(arg0);
            return result;
        }
    }
    async createPackTier(arg0: PackTierInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPackTier(await to_candid_PackTierInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPackTier(await to_candid_PackTierInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async delistCard(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.delistCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.delistCard(arg0);
            return result;
        }
    }
    async deposit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0);
            return result;
        }
    }
    async getActiveListings(): Promise<Array<Listing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveListings();
            return result;
        }
    }
    async getAllCards(): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCards();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCards();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRedemptions(): Promise<Array<Redemption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRedemptions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRedemptions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCard(arg0: bigint): Promise<Card> {
        if (this.processError) {
            try {
                const result = await this.actor.getCard(arg0);
                return from_candid_Card_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCard(arg0);
            return from_candid_Card_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCardsByIds(arg0: Array<bigint>): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardsByIds(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardsByIds(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCardsByOwner(arg0: Principal): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCardsByOwner(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCardsByOwner(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getMyRedemptions(): Promise<Array<Redemption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRedemptions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRedemptions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<{
        totalCards: bigint;
        activeListings: bigint;
        pendingRedemptions: bigint;
        totalUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isRegistered(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegistered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegistered(arg0);
            return result;
        }
    }
    async listCard(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.listCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCard(arg0, arg1);
            return result;
        }
    }
    async makeOffer(arg0: bigint, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.makeOffer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeOffer(arg0, arg1);
            return result;
        }
    }
    async mintCard(arg0: CardMintInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.mintCard(await to_candid_CardMintInput_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintCard(await to_candid_CardMintInput_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async openPack(arg0: bigint): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.openPack(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.openPack(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchasePack(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.purchasePack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchasePack(arg0);
            return result;
        }
    }
    async registerUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async rejectOffer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectOffer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectOffer(arg0);
            return result;
        }
    }
    async requestRedemption(arg0: bigint, arg1: {
        country: string;
        city: string;
        postalCode: string;
        name: string;
        state: string;
        addressLine1: string;
        addressLine2: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRedemption(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRedemption(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async transferCard(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferCard(arg0, arg1);
            return result;
        }
    }
    async updateRedemptionStatus(arg0: bigint, arg1: {
        __kind__: "shipped";
        shipped: string;
    } | {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "delivered";
        delivered: null;
    } | {
        __kind__: "processing";
        processing: null;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRedemptionStatus(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRedemptionStatus(arg0, to_candid_variant_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_Card_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Promise<Card> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Grade_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Grade): Grade {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Rarity_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rarity): Rarity {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Redemption_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Redemption): Redemption {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    setName: string;
    grader: string;
    owner: Principal;
    isListed: boolean;
    name: string;
    description: string;
    listingPrice: [] | [bigint];
    imageUrl: _ExternalBlob;
    grade: _Grade;
    rarity: _Rarity;
    cardNumber: string;
}): Promise<{
    id: bigint;
    setName: string;
    grader: string;
    owner: Principal;
    isListed: boolean;
    name: string;
    description: string;
    listingPrice?: bigint;
    imageUrl: ExternalBlob;
    grade: Grade;
    rarity: Rarity;
    cardNumber: string;
}> {
    return {
        id: value.id,
        setName: value.setName,
        grader: value.grader,
        owner: value.owner,
        isListed: value.isListed,
        name: value.name,
        description: value.description,
        listingPrice: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.listingPrice)),
        imageUrl: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.imageUrl),
        grade: from_candid_Grade_n17(_uploadFile, _downloadFile, value.grade),
        rarity: from_candid_Rarity_n19(_uploadFile, _downloadFile, value.rarity),
        cardNumber: value.cardNumber
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        shipped: string;
    } | {
        pending: null;
    } | {
        delivered: null;
    } | {
        processing: null;
    };
    owner: Principal;
    shippingAddress: {
        country: string;
        city: string;
        postalCode: string;
        name: string;
        state: string;
        addressLine1: string;
        addressLine2: string;
    };
    cardId: bigint;
}): {
    status: {
        __kind__: "shipped";
        shipped: string;
    } | {
        __kind__: "pending";
        pending: null;
    } | {
        __kind__: "delivered";
        delivered: null;
    } | {
        __kind__: "processing";
        processing: null;
    };
    owner: Principal;
    shippingAddress: {
        country: string;
        city: string;
        postalCode: string;
        name: string;
        state: string;
        addressLine1: string;
        addressLine2: string;
    };
    cardId: bigint;
} {
    return {
        status: from_candid_variant_n24(_uploadFile, _downloadFile, value.status),
        owner: value.owner,
        shippingAddress: value.shippingAddress,
        cardId: value.cardId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    raw: null;
} | {
    bgs9: null;
} | {
    psa7: null;
} | {
    psa8: null;
} | {
    psa9: null;
} | {
    bgs10: null;
} | {
    bgs85: null;
} | {
    bgs95: null;
} | {
    psa10: null;
}): Grade {
    return "raw" in value ? Grade.raw : "bgs9" in value ? Grade.bgs9 : "psa7" in value ? Grade.psa7 : "psa8" in value ? Grade.psa8 : "psa9" in value ? Grade.psa9 : "bgs10" in value ? Grade.bgs10 : "bgs85" in value ? Grade.bgs85 : "bgs95" in value ? Grade.bgs95 : "psa10" in value ? Grade.psa10 : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ultraRare: null;
} | {
    rare: null;
} | {
    secretRare: null;
} | {
    common: null;
} | {
    uncommon: null;
}): Rarity {
    return "ultraRare" in value ? Rarity.ultraRare : "rare" in value ? Rarity.rare : "secretRare" in value ? Rarity.secretRare : "common" in value ? Rarity.common : "uncommon" in value ? Rarity.uncommon : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: string;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    processing: null;
}): {
    __kind__: "shipped";
    shipped: string;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "delivered";
    delivered: null;
} | {
    __kind__: "processing";
    processing: null;
} {
    return "shipped" in value ? {
        __kind__: "shipped",
        shipped: value.shipped
    } : "pending" in value ? {
        __kind__: "pending",
        pending: value.pending
    } : "delivered" in value ? {
        __kind__: "delivered",
        delivered: value.delivered
    } : "processing" in value ? {
        __kind__: "processing",
        processing: value.processing
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Promise<Array<Card>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Card_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Redemption>): Array<Redemption> {
    return value.map((x)=>from_candid_Redemption_n22(_uploadFile, _downloadFile, x));
}
async function to_candid_CardMintInput_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardMintInput): Promise<_CardMintInput> {
    return await to_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Grade_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Grade): _Grade {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function to_candid_PackTierInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackTierInput): Promise<_PackTierInput> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Rarity_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rarity): _Rarity {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rarityWeights: {
        ultraRare: bigint;
        rare: bigint;
        secretRare: bigint;
        common: bigint;
        uncommon: bigint;
    };
    name: string;
    description: string;
    isActive: boolean;
    imageUrl: ExternalBlob;
    cardCount: bigint;
    price: bigint;
}): Promise<{
    rarityWeights: {
        ultraRare: bigint;
        rare: bigint;
        secretRare: bigint;
        common: bigint;
        uncommon: bigint;
    };
    name: string;
    description: string;
    isActive: boolean;
    imageUrl: _ExternalBlob;
    cardCount: bigint;
    price: bigint;
}> {
    return {
        rarityWeights: value.rarityWeights,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        imageUrl: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.imageUrl),
        cardCount: value.cardCount,
        price: value.price
    };
}
async function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    setName: string;
    grader: string;
    name: string;
    description: string;
    imageUrl: ExternalBlob;
    grade: Grade;
    rarity: Rarity;
    cardNumber: string;
}): Promise<{
    setName: string;
    grader: string;
    name: string;
    description: string;
    imageUrl: _ExternalBlob;
    grade: _Grade;
    rarity: _Rarity;
    cardNumber: string;
}> {
    return {
        setName: value.setName,
        grader: value.grader,
        name: value.name,
        description: value.description,
        imageUrl: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.imageUrl),
        grade: to_candid_Grade_n30(_uploadFile, _downloadFile, value.grade),
        rarity: to_candid_Rarity_n32(_uploadFile, _downloadFile, value.rarity),
        cardNumber: value.cardNumber
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Grade): {
    raw: null;
} | {
    bgs9: null;
} | {
    psa7: null;
} | {
    psa8: null;
} | {
    psa9: null;
} | {
    bgs10: null;
} | {
    bgs85: null;
} | {
    bgs95: null;
} | {
    psa10: null;
} {
    return value == Grade.raw ? {
        raw: null
    } : value == Grade.bgs9 ? {
        bgs9: null
    } : value == Grade.psa7 ? {
        psa7: null
    } : value == Grade.psa8 ? {
        psa8: null
    } : value == Grade.psa9 ? {
        psa9: null
    } : value == Grade.bgs10 ? {
        bgs10: null
    } : value == Grade.bgs85 ? {
        bgs85: null
    } : value == Grade.bgs95 ? {
        bgs95: null
    } : value == Grade.psa10 ? {
        psa10: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rarity): {
    ultraRare: null;
} | {
    rare: null;
} | {
    secretRare: null;
} | {
    common: null;
} | {
    uncommon: null;
} {
    return value == Rarity.ultraRare ? {
        ultraRare: null
    } : value == Rarity.rare ? {
        rare: null
    } : value == Rarity.secretRare ? {
        secretRare: null
    } : value == Rarity.common ? {
        common: null
    } : value == Rarity.uncommon ? {
        uncommon: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "shipped";
    shipped: string;
} | {
    __kind__: "pending";
    pending: null;
} | {
    __kind__: "delivered";
    delivered: null;
} | {
    __kind__: "processing";
    processing: null;
}): {
    shipped: string;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    processing: null;
} {
    return value.__kind__ === "shipped" ? {
        shipped: value.shipped
    } : value.__kind__ === "pending" ? {
        pending: value.pending
    } : value.__kind__ === "delivered" ? {
        delivered: value.delivered
    } : value.__kind__ === "processing" ? {
        processing: value.processing
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
